// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnS8JvTGMRQPFRgo1F6bWSqToRKMzgYeE',
    appId: '1:669034824282:web:76d1905ebb447340820e63',
    messagingSenderId: '669034824282',
    projectId: 'aonv2mr',
    authDomain: 'aonv2mr.firebaseapp.com',
    storageBucket: 'aonv2mr.appspot.com',
    measurementId: 'G-H29RX3NZQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9U8HtmoAO1yW560guVOWT0kGuhgfGWw',
    appId: '1:669034824282:android:bba58ab62a4da5b4820e63',
    messagingSenderId: '669034824282',
    projectId: 'aonv2mr',
    storageBucket: 'aonv2mr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rZWzDEGGcoel4fmxzrAfS4l40weiA1c',
    appId: '1:669034824282:ios:f9ac7a269d3fe405820e63',
    messagingSenderId: '669034824282',
    projectId: 'aonv2mr',
    storageBucket: 'aonv2mr.appspot.com',
    iosClientId: '669034824282-nfg88mb4hqe02l47gcccffmb1lsg0t07.apps.googleusercontent.com',
    iosBundleId: 'tv.kidfam.authonly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rZWzDEGGcoel4fmxzrAfS4l40weiA1c',
    appId: '1:669034824282:ios:87635d14a1075d05820e63',
    messagingSenderId: '669034824282',
    projectId: 'aonv2mr',
    storageBucket: 'aonv2mr.appspot.com',
    iosClientId: '669034824282-kfo7fq3phflutdmjdeq5deutc5jvjrcl.apps.googleusercontent.com',
    iosBundleId: 'tv.kidfam.authonly.RunnerTests',
  );
}
