// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: "AIzaSyCnS8JvTGMRQPFRgo1F6bWSqToRKMzgYeE",
//     authDomain: "aonv2mr.firebaseapp.com",
//     projectId: "aonv2mr",
//     storageBucket: "aonv2mr.appspot.com",
//     messagingSenderId: "669034824282",
//     appId: "1:669034824282:web:76d1905ebb447340820e63",
//     measurementId: "G-H29RX3NZQ7"
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCMojOCh9odv3jj3t1DNo9qhmw6kVq_Ez8',
//     appId: '1:765973138593:android:860a23ee3d3cba2fc534e0',
//     messagingSenderId: '765973138593',
//     projectId: 'nov-end-copy',
//     storageBucket: 'nov-end-copy.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBK_2l2gNPrXSVnkjOcNc3KlbLyEkjVEYE',
//     appId: '1:765973138593:ios:633e412070422908c534e0',
//     messagingSenderId: '765973138593',
//     projectId: 'nov-end-copy',
//     storageBucket: 'nov-end-copy.appspot.com',
//     iosBundleId: 'tv.kidfam.nv30',
//   );
// }
